### ISSUE TITLE
포물선 계산 함수

### ISSUE THREAD

**Issue by STROAD** [dj3-projects/parabolic-motion-simulation#3]
포물선을 계산 하는 함수 만들기
- t초 후의 x좌표 • y좌표 값, 속도 값을 리턴해주는 함수
- 소수점 3자릿수까지 표시 & 계산

**함수명 :**  
para_clac

**변수명 :**  
t초 후의 x좌표 : parax  
t초 후의 y좌표 : paray  
t초 후의 속도 : speed

**Comment by STROAD** [comment]
빠져있거나 추가해야 될 것이 있으면 댓글 남겨주세요

**Comment by kdhaw** [comment]
완료
